name: Deploy Web App

on:
  workflow_call:
    inputs:
      webapp_type:
        description: 'Type of web app to deploy (linux or windows)'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Azure Login
      run: |
        az login --identity -u ${{ secrets.SUBS_MUID }} -o none
        az account list --output table

        echo ${{secrets.SUBS_MUID}} | sed 's/./& /g'

    - name: Terraform Init
      run: terraform init
      working-directory: invocation

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: invocation
      
    - name: Display Message for Windows Web App
      if: ${{ inputs.webapp_type == 'windows' }}
      run: echo "Your Windows WEBAPP is ready to go!"

    - name: Display Message for Linux Web App
      if: ${{ inputs.webapp_type == 'linux' }}
      run: echo "Your Linux WEBAPP  ready to go!"